### ISSUE TITLE
BUG ・PathBuf not working on MacOS

### ISSUE THREAD

**Issue by dimkauzh** [ThatFrogDev/notaben#26] opened 2023-07-18 21:44 UTC
### Before you start, first check the following:

- [X] I have searched the issues and confirmed that this is not a duplicate or a known issue.
- [X] I am on the newest version of Notabena.

### Are you facing this issue using Notabena CLI or Desktop?

CLI

### What platform are you using Notabena on?

macOS

### What kind of bug are you facing?

Hi,
So i tried running notabena by ``` cargo run ```, but it gave me this error:
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/notabena`
PathBuf { inner: "/Users/dmarhitych-pro/Library/Notabena" }
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
I don't understand why.
Can you help me?

### How to reproduce the bug?

1. Cargo run on macos

### What did you expect that would happen?

To just run

### Can you send us some screenshots?

<img width="649" alt="Screenshot 2023-07-18 at 23 44 10" src="https://github.com/ThatFrogDev/notabena/assets/106883655/3d79bf24-6c9d-4500-aaae-f3ffc203be62">

**Comment by SwiftDust** [comment] 2023-07-19 06:00
That's weird! It's probably to do with the macOS version, but what was your expected path? If you provide that we can add checks for it

**Comment by ThatFrogDev** [comment] 2023-07-19 06:11
That's weird! It's probably to do with the macOS version, but what was your expected path? If you provide that we can add checks for it

**Comment by dimkauzh** [comment] 2023-07-21 18:18
What should I provide? If you tell me everything I need to provide then I will provide you with it @ThatFrogDev

**Comment by SwiftDust** [comment] 2023-07-21 18:28
> What should I provide? If you tell me everything I need to provide then I will provide you with it @ThatFrogDev 

The path where all program files are stored (on macOS the default is `~/Library`)

**Comment by dimkauzh** [comment] 2023-07-22 11:19
> > What should I provide? If you tell me everything I need to provide then I will provide you with it @ThatFrogDev 
> 
> The path where all program files are stored (on macOS the default is `~/Library`)

Normally it's in the app it's self, because you need special privileges for '~/Library. Because the app is normally with .app ending, it normally stores there it's data

**Comment by SwiftDust** [comment] 2023-07-22 15:45
> > > What should I provide? If you tell me everything I need to provide then I will provide you with it @ThatFrogDev 
> > 
> > The path where all program files are stored (on macOS the default is `~/Library`)
> 
> Normally it's in the app it's self, because you need special privileges for '~/Library. Because the app is normally with .app ending, it normally stores there it's data

Ahhh okay, I don't know how to fix this though, maybe I can compile it to the .app format but I have no idea how yet

**Comment by MrSerge01** [comment] 2023-07-27 15:48
hello! the error appeared on Windows too, Notabena thought that `C:\Users\user\AppData\Notabena` was the path (it's supposed to be `C:\Users\user\AppData\Roaming\Notabena`.
The issue is fixed in the commit I'm working on. #25

**Closed as completed** 2023-08-27 12:27 UTC
Labels: bug
